#!/usr/bin/python3.5
# -*-coding:Utf-8 -*

import random
import operator
import time
import matplotlib.pyplot as plt

temps1 = time.time()

#genetic algorithm function
def generate_one_item(Max_weight, Max_value):
	item = []
	item.append(round(Max_weight * random.random()))
	item.append(round(Max_value * random.random()))
	return item
	
def generate_all_items(Number_of_item, Max_weight, Max_value):
	list_item = []
	for i in range(Number_of_item):
		list_item.append(generate_one_item(Max_weight, Max_value))
	return list_item

def total_weight_of_item_set(item_set):
	total_weight = 0
	for item in item_set:
		total_weight += item[0]
	return total_weight

def generate_one_individual(item_set):
	individual = []
	for i in range (len(item_set)):
		if (100 * random.random() < 50):
			individual.append(True)
		else:
			individual.append(False)
	return individual

def to_string_individual(individual):
	result = ""
	for boolean in individual:
		if (boolean):
			result += "T"
		else:
			result += "F"
	return result

def generate_individual_from_string(string_individual):
	result = []
	for letter in string_individual:
		if letter == 'F':
			result.append(False)
		else:
			result.append(True)
	return result

def generate_first_population(item_set, size_of_population):
	population = []
	for i in range(size_of_population):
		population.append(generate_one_individual(item_set))
	return population

def weight_of_individual(individual, item_set):
	weight = 0
	for i in range(len(individual)):
		if (individual[i]):
			weight += item_set[i][0]
	return weight
	
def value_of_individual(individual, item_set):
	value = 0
	for i in range(len(individual)):
		if (individual[i]):
			value += item_set[i][1]
	return value

def fitness(individual, item_set):
	Knapsack_Capacity = round(total_weight_of_item_set(item_set) / 2)
	result = 0
	if (weight_of_individual(individual, item_set) <= Knapsack_Capacity):
		result = value_of_individual(individual, item_set)
	return result 

def sort_population_by_fitness(population, item_set):
	population_sorted = {}
	for individual in population:
		population_sorted[to_string_individual(individual)] = fitness(individual, item_set)
	return sorted(population_sorted.items(), key = operator.itemgetter(1), reverse = True)

def select_breeders(population_sorted, item_set, best_individuals, lucky_few):
	result = []
	for i in range(best_individuals):
		result.append(generate_individual_from_string(population_sorted[i][0]))
	for i in range(lucky_few):
		result.append(generate_individual_from_string(random.choice(population_sorted)[0]))
	random.shuffle(result)
	return result

def create_child(individual1, individual2):
	result = []
	for i in range(len(individual1)):
		if (100 * random.random() < 50):
			result.append(individual1[i])
		else:
			result.append(individual2[i])
	return result

#print result:

#variables
#Knapsack_Capacity = item_set_total_weight / 2
Number_of_item = 20
Max_value = 10
Max_weight = 10

size_of_population = 100
best_individuals = 20
lucky_few = 20

#main
item_set = generate_all_items(Number_of_item, Max_weight, Max_value)
population = generate_first_population(item_set, size_of_population)
population_sorted = sort_population_by_fitness(population, item_set)
breeders = select_breeders(population_sorted, item_set, best_individuals, lucky_few)
individual1 = generate_one_individual(item_set)
print to_string_individual(individual1)
individual2 = generate_one_individual(item_set)
print to_string_individual(individual2)
print to_string_individual(create_child(individual1, individual2))

#analysis tools
def compute_average_total_weight(size_sample, Number_of_item, Max_weight, Max_value):
	average_total_weight = 0
	for i in range (size_sample):
		item_set = generate_all_items(Number_of_item, Max_weight, Max_value)
		total_weight = total_weight_of_item_set(item_set)
		average_total_weight += total_weight
	print(average_total_weight/size_sample)
#size_sample = 100
#compute_average_total_weight(size_sample, Number_of_item, Max_weight, Max_value)

print time.time() - temps1
